spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/association?characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.association.user.model
  configuration:
    map-underscore-to-camel-case: true

user:
  token:
    life: 14
    unit: DAYS
role:
  common: 1234 # todo 修改为普通用户guid