nacos:
  config:
    test: 1
    props:
      - group: association
        dataId: school
      - group: association
        dataId: category
      - group: association
        dataId: auth

spring:
  main:
    allow-bean-definition-overriding: true
